# ENCH 470 Spring 2024 Assignment 3

## Antoine's equation

Antoine's equation correlates the saturated vapor pressure $P^{sat}$ and temperature $T$ for pure species in vapor-liquid equilibrium.

$$ \log _{{10}}P^{sat}=A-{\frac  {B}{C+T}}.$$

where $P^{sat}$ units are $[mmHg]$ and $T$ units are $[°C]$ (or whatever units your source has you using)

Here's a simple function that does the job:

In [1]:
from calc_antoine import antoine

In [2]:
def antoine( a, T ):
    """Antoine's equation calculator
    
    This uses Antoine's equation to calculate the vapor pressure of a fluid
    given the coefficients of the equation: Ps = a1 - a2/(a3 + T).
    
    Parameters
    ----------
    a :the Antoine coefficients with coefficients in columns and species in rows.
    T : the temperature to evaluate the vapor pressure at.
    
    Returns
    -------
    Ps : row vector of vapor pressures for all species at the specified temperature

    The units depend on the units used for the coefficients.  The user is
    responsible for maintaining consistency with units.  Customarily,
    coefficients are supplied for pressure in mmHg and T in Celsius.
    
    Examples
    --------
    >>> Ps = antoine(a, T)
    
    """
    
    Ps = 10.0**( a[:,0]-a[:,1] / ( a[:,2] + T ) )
    return Ps
    
def raoults_law_k_values(a, T, P):
    """
    Calculate K-values using Raoult's Law.
    
    Parameters:
    - T: Temperature in Kelvin
    - P: Total pressure in mmHg
    - a: containing coefficients matrix a for Antoine's equation
    
    Returns:
    List of K values for each component
    """
    
    Pa = antoine(a,T)
    K = Pa / P  # Raoult's Law
    
    return K

<font color=red>**Problem:**</font> Write a function to calculate K-values at a given T and P using Raoult's Law and obtaining the vapor pressure from Antoine's equation. https://en.wikipedia.org/wiki/Vapor–liquid_equilibrium#K_values_and_relative_volatility_values You may use the provided function `antoine` from `calc_antoine.py`; if you use your own function for Antoine's equation, please provide it in this notebook.

In [3]:
from raoult_law import raoults_law_k_values as rkl

<font color=red>**Problem:**</font> Document this function using appropriate docstring convention.

In [4]:
help(rkl)

Help on function raoults_law_k_values in module raoult_law:

raoults_law_k_values(a, T, P)
    Calculate K-values using Raoult's Law.
    
    Parameters:
    - T: Temperature in Kelvin
    - P: Total pressure in mmHg
    - a: containing coefficients matrix a for Antoine's equation
    
    Returns:
    List of K values for each component



In [6]:
import numpy as np

<font color=red>**Problem:**</font> Calculate the K-values for propane and benzene at 101325 Pa and 300 K. Coefficents are from the NIST Webbook and are compatible with units of bar and K.

In [7]:
propane = [4.53678, 1149.36, 24.906]
benzene = [0.14591, 39.165, -261.236]
a = np.array([propane,benzene])
#y = antoine(x,T)
P = 101325
P_new = 101325/100000 #bar
T = 300 # K
rkl(a,T,P_new)

array([9.85253353, 0.13484931])

<font color=red>**Problem:**</font> Use the answer from the previous problem to create a test for verifying the K-value function. Document this test function using docstrings.

In [8]:
def test1():
    # Parameters
    A = 4.53678
    B = 1149.36
    C = 24.906 
    T = 300

    Psat = 9.85
    
    if abs(rkl(a,T,P_new)[0] - Psat) < 0.01:
        print("test passed")
    else:
        print("test failed")

def test2():
    # Parameters
    A = 0.14591
    B = 39.165
    C = -261.236 
    T = 300

    Psat = 0.13
    
    if abs(rkl(a,T,P_new)[1] - Psat) < 0.01:
        print("test passed")
    else:
        print("test failed")
        
print(test1(),test2())

test passed
test passed
None None


In [9]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.reshape(A, (3,2))
B

array([[1, 2],
       [3, 4],
       [5, 6]])

<font color=red>**Problem:**</font> For the array `B` above, calculate the mean of each row and calculate the mean of each column, clearly labeling each case. Tip: read the docs on how `mean` works for multidimensional arrays.

In [10]:
# Calculate the mean of each row (along axis 1)
r_means = np.mean(B, axis=1)

# Calculate the mean of each column (along axis 0)
c_means = np.mean(B, axis=0)

print("Mean of each row:")
print(r_means)

print("\nMean of each column:")
print(c_means)


Mean of each row:
[1.5 3.5 5.5]

Mean of each column:
[3. 4.]


<font color=red>**Problem:**</font> Consider the dataset below. Count the number of measurements, calculate the mean and standard deviation of the data. Print the standard deviation with 1 significant digit and print the mean with the same precision. Your code may specify the number of digits manually in this answer.

For example, if the mean is 5.2112332 and the standard deviation is 0.02332, then you should print 5.21 +/- 0.02.

In [11]:
Measurements = np.array([0.00245234, 0.00245524, 0.00248823, 0.002499234, 0.00242256])

# Count the number of measurements
num_measurements = len(Measurements)

# Calculate mean and standard deviation
mean_value = np.mean(Measurements)
std_dev_value = np.std(Measurements, ddof=1)  # ddof=1 for sample standard deviation

# Format mean and standard deviation with 1 significant digit
formatted_mean = f"{mean_value:.1g}"
formatted_std_dev = f"{std_dev_value:.1g}"

# Print the result
print(num_measurements)
print(mean_value)
print(std_dev_value)
print('Average of', num_measurements, 'measurements is', formatted_mean, '+/-', formatted_std_dev) 

5
0.0024635207999999997
3.064859822569385e-05
Average of 5 measurements is 0.002 +/- 3e-05


<font color=orange>**Extra Credit:**</font> Do the same across the rows of the data below. Have your code detect the number of signficant figures (based on the standard deviation) and use that to format the number of digits for the mean. You may not specify the number of digits manually.

In [12]:
MoreData = {'Concentration':[0.00245234, 0.00245524, 0.00248823, 0.002499234, 0.00242256],
            'Number of particles':[527283, 557398, 598720, 605402, 515654],
            'Solubility':[0.551, 0.245, 0.456, 0.378, 0.345]}

In [35]:
MoreData = {'Concentration': [0.00245234, 0.00245524, 0.00248823, 0.002499234, 0.00242256],
            'Number of particles': [527283, 557398, 598720, 605402, 515654],
            'Solubility': [0.551, 0.245, 0.456, 0.378, 0.345]}

def calculate_and_format(data):
    result = {}
    
    for key, values in data.items():
        mean_value = np.mean(values)
        std_dev_value = np.std(values, ddof=1)
        
        # Determine the number of significant figures based on the standard deviation
        num_significant_figures = len(str(std_dev_value).split('.')[-1])
        
        # Format mean and standard deviation
        formatted_mean = f"{mean_value:.{num_significant_figures}g}"
        formatted_std_dev = f"{std_dev_value:.{num_significant_figures}g}"
        
        result[key] = {'Mean': formatted_mean, 'Standard Deviation': formatted_std_dev}
    
    return result

result = calculate_and_format(MoreData)

# Print the result
for key, values in result.items():
    print(f"\n{key}:")
    print(f"  Mean: {values['Mean']} +/- {values['Standard Deviation']}")



Concentration:
  Mean: 0.002463520799999999698 +/- 3.064859822569385102e-05

Number of particles:
  Mean: 560891.4 +/- 40621.2605762

Solubility:
  Mean: 0.395 +/- 0.115483765092761


<font color=red>**Problem:**</font> Look up 3 additional numpy functions and methods and show an example for each.

In [13]:
result = np.arange(10)
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
ones_array = np.ones((3, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
data = np.array([[1, 2, 3], [4, 5, 6]])
sum_result = np.sum(data, axis=1)
print(sum_result)

[ 6 15]
